[package]
name = "hypixel-bank-tracker"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12"
dotenvy = "0.15"
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
